backend:
  name: git-gateway
  branch: main # Make sure your GitHub branch is actually named 'main' (or change to 'master')

media_folder: "Gallery Images"
public_folder: "Gallery Images"

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "gallery.json"
        label: "Gallery Photos"
        name: "gallery"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            field: {label: "Photo", name: "image", widget: "image"}